staticSites:
  - name: loveapplication-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: Content-Type
        value: text/html
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html