services:
  - type: web
    name: loveaplication-backend
    env: python
    region: singapore  # или singapore, oregon, ohio
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FRONTEND_URL
        value: https://loveaplication-frontend.onrender.com
      - key: CORS_ORIGINS
        value: https://loveaplication-frontend.onrender.com,http://localhost:3000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: loveapp-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    autoDeploy: true

  - type: web
      name: PgHero-dpg-d60t5svfte5s73bes350-a
      env: docker
      dockerfilePath: Dockerfile.pghero
      envVars:
        - key: DATABASE_URL
          fromDatabase:
            name: loveapp-db  # имя вашей БД на Render
            property: connectionString
        - key: PGHERO_USERNAME
          value: pghero-f39be2f7
        - key: PGHERO_PASSWORD
          value: fa6b7cedf03eae11c3acc084e167ff45
      plan: free